### ISSUE TITLE
JSON parsing library , sample codes

### ISSUE THREAD

**Issue by ghost** [OZMOPOL/OZMO-ANDROID#1]

**Comment by arcadesmasher** [comment]
Dropping three examples for now, more to come:

Fundamental: http://androidexample.com/JSON_Parsing_-_Android_Example/index.php?view=article_discription&aid=71&aaid=95

With HTTP-stuff such as GET/POST: http://www.androidhive.info/2012/01/android-json-parsing-tutorial/

With HTTP-stuff, nicely polished, uses JSON's embedded in PHP pages: https://www.codeofaninja.com/2013/11/android-json-parsing-tutorial.html

**Comment by ghost** [comment]
The most popular and robust library I found is "Retrofit" (  http://square.github.io/retrofit/ )
We're gonna use this library as RESTful Client in our Android APP.
