### ISSUE TITLE
Phone UI

### ISSUE THREAD

**Issue by ghost** [OZMOPOL/OZMO-ANDROID#11]
@arcadesmasher could you please modify post_item.xml to be shown in a phone without bugs.

**Comment by arcadesmasher** [comment]
I'm currently on it, the posts are properly displayed when the phone is rotated, though.

**Comment by arcadesmasher** [comment]
Update: The problem happens when the dates and the room info. for the posts are obtained. The info. are way too long and they push the post title & contents way a lot.

```
        vh.postCDate.setText(post.postCDate);
        vh.room.setText(post.fkPostRoomId.roomTitle);
```

I will try to fit the dates & room info. to the sizes that a phone screen can accept.

**Comment by ghost** [comment]
Try changing font sizes unit from dp to sp.

**Comment by arcadesmasher** [comment]
It's about the width/height of the date & room info. I'm currently messing with those.

**Comment by arcadesmasher** [comment]
The room names and the dates were too long so I've initiated another horizontal LinearLayout under the horizontal LinearLayout where the user, date, room info. were stored, then moved the room info under that sub LinearLayout and decreased the font sizes a bit.

Problem solved.
