### ISSUE TITLE
Issue in PostsAdapter text & button functions

### ISSUE THREAD

**Issue by arcadesmasher** [OZMOPOL/OZMO-ANDROID#3]
This issue needn't be solved asap right now, but is necessary in the future.

PostsAdapter.java, line 74: where should those functions be run at, in order to give functionality to the elements of /each post at the front page?

**Comment by ugurcant** [comment]
why would be anything different to vote a post on room or on front page? I think it will work for it

**Comment by arcadesmasher** [comment]
Issue solved and closed by self.
