### ISSUE TITLE
Pull-To-Refresh functionality

### ISSUE THREAD

**Issue by ghost** [OZMOPOL/OZMO-ANDROID#6]
We need to refresh the FragmentFrontPage by adding pull-to-refresh functionality to it, so we could use Google native components.

**Comment by ghost** [comment]
https://github.com/stormzhang/SwipeRefreshLayoutDemo

**Comment by arcadesmasher** [comment]
The application now has the function to refresh data when the screen is pulled downwards.

Issue closed.
